### ISSUE TITLE
Winston?

### ISSUE THREAD

**Issue by edasque** [jongarrison/slush-nodebb-plugin#2]
The following line:

```
winston.verbose("nodebb-plugin-constantcontact - staticAppLoad called");
```

doesn't seem to output anything in my nodebb 0.8.x install (I am not saying it's specific to that version, it's just the only version I am running). Where is Winston supposed to be logging. Is there something else that needs to happen for it to work? If I understand correctly Winston default behavior is to use console.log as the only logging provider, AFAIK yet

```
console.log("nodebb-plugin-constantcontact - staticAppLoad called");
```

works, obviously.

**Comment by jongarrison** [comment]
Hi, Winston is the logging framework that NodeBB uses internally and so it reports messages based on the logging level that NodeBB is set at.  If you run NodeBB in dev mode, it outputs "verbose" level log messages and I think when running NodeBB in production mode (the default start option) it probably only logs at "info" or higher (like "warn" or "error").

Try starting Nodebb with "./nodbb dev" (or change the Winston call from "verbose" to "info") to see the messages appear in your logs.

**Comment by edasque** [comment]
Thank you for your response. Makes sense to me now.

**Comment by jongarrison** [comment]
Cool, you're welcome!
